"""Updated model

Revision ID: c12c4ce36c08
Revises: f82629f382e8
Create Date: 2024-02-13 21:01:10.205121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12c4ce36c08'
down_revision = 'f82629f382e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
